additionalProperties:
  npmName: '@busyas/test-client'
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
  generateAliasAsModel: false
  
globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
  generateAliasAsModel: false
