# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  # Every hour
  #- cron:  '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-ts-client:
      runs-on: ubuntu-latest
      name: Generate TypeScript client
      steps:

        # Checkout your code
        - name: Checkout
          uses: actions/checkout@v2

        # Generate your OpenAPI document (if you don't write it manually)

        # Use the action to generate a client package
        # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
        - name: Generate TypeScript Client
          uses: openapi-generators/openapitools-generator-action@v1
          with:
            generator: javascript
            config-file: typescript-fetch-generator-config.yml
            openapi-url: https://tripletex.no/v2/swagger.json

        # Do something with the generated client (likely publishing it somewhere)
        - name: Do something with the client
          run: |
            cd javascript-client
            ls
